<?php

namespace Database\Seeders;

use App\Models\Certificate;
use App\Models\Course;
use Illuminate\Database\Seeder;

class CertificateSeeder extends Seeder
{
    public function run(): void
    {
        $lashesCourse = Course::where('slug', 'master-lashes-artistry')->first();
        $makeupCourse = Course::where('slug', 'pro-makeup-masterclass')->first();

        $certificates = [
            [
                'certificate_number' => 'DH-2026-0812',
                'student_name' => 'IRAGENA JEANETTE (ANITHA)',
                'student_email' => 'iragena.jeanette@gmail.com',
                'course_name' => 'Professional Lashes & Makeup Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-21',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Rubavu Rwanda Branch',
                'is_valid' => true,
                'notes' => 'Completed professional lashes & makeup artistry training with distinction.',
            ],
            [
                'certificate_number' => 'DH-2026-0821',
                'student_name' => "Monicah Ndung'u",
                'student_email' => 'monicah.ndungu@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0822',
                'student_name' => 'Nikki Nicole',
                'student_email' => 'nikki.nicole@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0823',
                'student_name' => 'Ruth Nduta',
                'student_email' => 'ruth.nduta@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0824',
                'student_name' => 'Kensley Abigail Wairimu',
                'student_email' => 'kensley.abigail@gmail.com',
                'course_name' => 'Professional Lashes & Makeup Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed combined pro lashes & makeup artistry training.',
            ],
            [
                'certificate_number' => 'DH-2026-0825',
                'student_name' => 'Vivian Wambui Kanyiri',
                'student_email' => 'vivian.kanyiri@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0826',
                'student_name' => 'Sophia Njeri',
                'student_email' => 'sophia.njeri@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0827',
                'student_name' => 'Assoumpta Uwanyiligira',
                'student_email' => 'assoumpta.u@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0828',
                'student_name' => 'Stephanie Kabura Mwinga',
                'student_email' => 'stephanie.mwinga@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0829',
                'student_name' => "Irene Muthoni Ng'ang'a",
                'student_email' => 'irene.nganga@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0830',
                'student_name' => 'Rose Wairimu',
                'student_email' => 'rose.wairimu@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0831',
                'student_name' => 'Wendy Wanjiru Maina',
                'student_email' => 'wendy.maina@gmail.com',
                'course_name' => 'Professional Lashes & Makeup Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed combined pro lashes & makeup artistry training.',
            ],
            [
                'certificate_number' => 'DH-2026-0832',
                'student_name' => 'Lucy Mwikali',
                'student_email' => 'lucy.mwikali@gmail.com',
                'course_name' => 'Professional Lashes & Makeup Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed combined pro lashes & makeup artistry training.',
            ],
            [
                'certificate_number' => 'DH-2026-0833',
                'student_name' => 'Joy Bironga',
                'student_email' => 'joy.bironga@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0834',
                'student_name' => 'Weddy Kinya',
                'student_email' => 'weddy.kinya@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0835',
                'student_name' => 'Scola Mwangi',
                'student_email' => 'scola.mwangi@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0836',
                'student_name' => 'Malaak Karzym',
                'student_email' => 'malaak.karzym@gmail.com',
                'course_name' => 'Professional Makeup Training',
                'course_id' => $makeupCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional makeup artistry training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0837',
                'student_name' => 'Redempta Sharon Wekesa',
                'student_email' => 'redempta.wekesa@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
            [
                'certificate_number' => 'DH-2026-0838',
                'student_name' => 'Lorine Odhiambo',
                'student_email' => 'lorine.odhiambo@gmail.com',
                'course_name' => 'Professional Lashes Training',
                'course_id' => $lashesCourse?->id,
                'issue_date' => '2026-09-24',
                'grade' => 'Certified Specialist with Honors',
                'location' => 'diva house beauty (E.A.C) - Nairobi Kenya Branch',
                'is_valid' => true,
                'notes' => 'Successfully completed professional lashes training module.',
            ],
        ];

        foreach ($certificates as $cert) {
            Certificate::updateOrCreate(
                ['certificate_number' => $cert['certificate_number']],
                $cert
            );
        }
    }
}
