<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Review;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $reviews = [
            [
                'student_name' => 'Keza Grace',
                'avatar_initials' => 'KG',
                'role_title' => 'Certified Lash Artist',
                'location' => 'Kigali',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "The Lashes Artistry course at Kigali campus completely elevated my career. The hands-on model training and professional kit gave me everything I needed to open my own studio!",
                'is_featured' => true,
                'order' => 1,
            ],
            [
                'student_name' => 'Amina Wanjiku',
                'avatar_initials' => 'AW',
                'role_title' => 'Pro Makeup Artist',
                'location' => 'Nairobi',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "The Pro Makeup Masterclass in Nairobi taught me high-end bridal techniques and color matching for all skin tones. The instructors are world-class mentors.",
                'is_featured' => true,
                'order' => 2,
            ],
            [
                'student_name' => 'Brenda Hassan',
                'avatar_initials' => 'BH',
                'role_title' => 'Beauty Entrepreneur',
                'location' => 'Mombasa',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "The business coaching module was a game changer. I learned client retention, pricing strategy, and social media branding for my coastal studio.",
                'is_featured' => true,
                'order' => 3,
            ],
            [
                'student_name' => 'Diane Uwase',
                'avatar_initials' => 'DU',
                'role_title' => 'Bridal Makeup Specialist',
                'location' => 'Kigali',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "Starting my beauty journey at Diva House Academy was the best decision. The practical sessions on live models built my confidence tremendously.",
                'is_featured' => true,
                'order' => 4,
            ],
            [
                'student_name' => 'Faith Chebet',
                'avatar_initials' => 'FC',
                'role_title' => 'Volume Lash Specialist',
                'location' => 'Nairobi',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "The isolation and fanning techniques taught in the volume lash module are top tier. I booked 15 clients in my first month after graduation.",
                'is_featured' => true,
                'order' => 5,
            ],
            [
                'student_name' => 'Joy Kwizera',
                'avatar_initials' => 'JK',
                'role_title' => 'Lash & Brow Stylist',
                'location' => 'Kigali',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "I loved how detailed the lash lift and brow lamination units were. The starter kit was packed with premium products.",
                'is_featured' => true,
                'order' => 6,
            ],
            [
                'student_name' => 'Sharon Muthoni',
                'avatar_initials' => 'SM',
                'role_title' => 'High-Fashion MUA',
                'location' => 'Nairobi',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "The bridal glam and cut crease techniques opened so many doors for me. I now do makeup for luxury weddings across Kenya.",
                'is_featured' => true,
                'order' => 7,
            ],
            [
                'student_name' => 'Sarah Nyambura',
                'avatar_initials' => 'SN',
                'role_title' => 'Studio Owner',
                'location' => 'Mombasa',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "From skin prep to setting high-fashion editorial looks, the trainers at Mombasa studio pay attention to every detail.",
                'is_featured' => true,
                'order' => 8,
            ],
            [
                'student_name' => 'Chantal Mutoni',
                'avatar_initials' => 'CM',
                'role_title' => 'Certified Beauty Tech',
                'location' => 'Kigali',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "The small class size allowed master trainers to give personalized feedback on every step of my makeup application.",
                'is_featured' => true,
                'order' => 9,
            ],
            [
                'student_name' => 'Mercy Akinyi',
                'avatar_initials' => 'MA',
                'role_title' => 'Lash Technician',
                'location' => 'Nairobi',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "Learning hygiene, eye anatomy, and proper adhesive usage gave me full confidence as a certified lash artist.",
                'is_featured' => true,
                'order' => 10,
            ],
            [
                'student_name' => 'Sonia Ingabire',
                'avatar_initials' => 'SI',
                'role_title' => 'Lash Studio Owner',
                'location' => 'Kigali',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "I transitioned from a full-time office job to running my own eyelash salon in Kigali. Highly recommended masterclass!",
                'is_featured' => true,
                'order' => 11,
            ],
            [
                'student_name' => 'Mary Njeri',
                'avatar_initials' => 'MN',
                'role_title' => 'Pro MUA',
                'location' => 'Nairobi',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "The color theory and contouring modules were mind-blowing. I can confidently match any skin tone flawlessly.",
                'is_featured' => true,
                'order' => 12,
            ],
            [
                'student_name' => 'Halima Ali',
                'avatar_initials' => 'HA',
                'role_title' => 'Lash Specialist',
                'location' => 'Mombasa',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "The flexible weekend schedules allowed me to complete my certification while working. Amazing environment and mentors.",
                'is_featured' => true,
                'order' => 13,
            ],
            [
                'student_name' => 'Aline Nishimwe',
                'avatar_initials' => 'AN',
                'role_title' => 'Certified MUA',
                'location' => 'Kigali',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "The practical exams and live model feedback prepared me for real salon clients from day one.",
                'is_featured' => true,
                'order' => 14,
            ],
            [
                'student_name' => 'Esther Kilonzo',
                'avatar_initials' => 'EK',
                'role_title' => 'Lash Extension Specialist',
                'location' => 'Nairobi',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "Mega volume application and mapping techniques were taught so clearly. The studio setup is world-class.",
                'is_featured' => true,
                'order' => 15,
            ],
            [
                'student_name' => 'Nadia Umutoni',
                'avatar_initials' => 'NU',
                'role_title' => 'Certified Lash Artist',
                'location' => 'Kigali',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "The professional starter kit alone is worth the tuition. High quality lash trays and ergonomic tweezers included.",
                'is_featured' => true,
                'order' => 16,
            ],
            [
                'student_name' => 'Grace Otieno',
                'avatar_initials' => 'GO',
                'role_title' => 'Beauty Entrepreneur',
                'location' => 'Nairobi',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "I learned how to price my services competitively and market my portfolio on Instagram. Business coaching was invaluable.",
                'is_featured' => true,
                'order' => 17,
            ],
            [
                'student_name' => 'Patricia Mukamana',
                'avatar_initials' => 'PM',
                'role_title' => 'Red Carpet MUA',
                'location' => 'Kigali',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "Learning soft glam and red carpet makeup techniques helped me gain celebrity clients in Kigali.",
                'is_featured' => true,
                'order' => 18,
            ],
            [
                'student_name' => 'Rehema Bakari',
                'avatar_initials' => 'RB',
                'role_title' => 'Bridal Specialist',
                'location' => 'Mombasa',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "The coastal humidity makeup setting techniques were so helpful for my wedding clients in Mombasa!",
                'is_featured' => true,
                'order' => 19,
            ],
            [
                'student_name' => 'Jackline Cherono',
                'avatar_initials' => 'JC',
                'role_title' => 'Lash Artist',
                'location' => 'Nairobi',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "Classic, hybrid, and volume extensions mastery in just a few weeks. The mentors are patient and skilled.",
                'is_featured' => true,
                'order' => 20,
            ],
            [
                'student_name' => 'Valentine Gasana',
                'avatar_initials' => 'VG',
                'role_title' => 'Lash Technician',
                'location' => 'Kigali',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "Cleanliness, eye isolation, and zero clumping rules were emphasized. My clients always compliment the retention!",
                'is_featured' => true,
                'order' => 21,
            ],
            [
                'student_name' => 'Caroline Wambui',
                'avatar_initials' => 'CW',
                'role_title' => 'Pro MUA',
                'location' => 'Nairobi',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "The hands-on practice with different skin types was incredible. Best makeup academy in East Africa.",
                'is_featured' => true,
                'order' => 22,
            ],
            [
                'student_name' => 'Beatrice Iradukunda',
                'avatar_initials' => 'BI',
                'role_title' => 'Lead Salon MUA',
                'location' => 'Kigali',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "The diploma certification is recognized everywhere. I landed a lead MUA role at a top salon right after.",
                'is_featured' => true,
                'order' => 23,
            ],
            [
                'student_name' => 'Fatuma Mohamed',
                'avatar_initials' => 'FM',
                'role_title' => 'Lash & Brow Stylist',
                'location' => 'Mombasa',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "Lash lifts and tinting techniques gave me a quick-service add-on for my salon menu.",
                'is_featured' => true,
                'order' => 24,
            ],
            [
                'student_name' => 'Rose Adhiambo',
                'avatar_initials' => 'RA',
                'role_title' => 'Certified Lash Tech',
                'location' => 'Nairobi',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "I gained lifelong mentorship and joined a supportive alumni network of lash technicians across Kenya.",
                'is_featured' => true,
                'order' => 25,
            ],
            [
                'student_name' => 'Sandrine Mutesi',
                'avatar_initials' => 'SM',
                'role_title' => 'Studio Founder',
                'location' => 'Kigali',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "The practical stations at Kigali campus are super modern and well equipped. I felt like a pro from day one.",
                'is_featured' => true,
                'order' => 26,
            ],
            [
                'student_name' => 'Nancy Gitau',
                'avatar_initials' => 'NG',
                'role_title' => 'Pro Makeup Artist',
                'location' => 'Nairobi',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "The speed and precision drills helped me cut down my client makeover time without sacrificing quality.",
                'is_featured' => true,
                'order' => 27,
            ],
            [
                'student_name' => 'Devota Bugingo',
                'avatar_initials' => 'DB',
                'role_title' => 'Editorial MUA',
                'location' => 'Kigali',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "High fashion, editorial, and bridal looks were taught step-by-step. Super inspiring atmosphere!",
                'is_featured' => true,
                'order' => 28,
            ],
            [
                'student_name' => 'Leila Omar',
                'avatar_initials' => 'LO',
                'role_title' => 'Bridal Beauty Artist',
                'location' => 'Mombasa',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "Learning waterproof airbrush-like finish makeup for humid weather was a game changer for my Mombasa studio.",
                'is_featured' => true,
                'order' => 29,
            ],
            [
                'student_name' => 'Gladys Kiprop',
                'avatar_initials' => 'GK',
                'role_title' => 'Lash Artist',
                'location' => 'Nairobi',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "From client consultations to lash mapping according to eye shape, everything was covered thoroughly.",
                'is_featured' => true,
                'order' => 30,
            ],
            [
                'student_name' => 'Claudine Akimana',
                'avatar_initials' => 'CA',
                'role_title' => 'Certified Lash Specialist',
                'location' => 'Kigali',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "The certificate gave me immediate credibility with clients. My booking calendar is full weeks in advance.",
                'is_featured' => true,
                'order' => 31,
            ],
            [
                'student_name' => 'Hellen Odhiambo',
                'avatar_initials' => 'HO',
                'role_title' => 'Pro MUA',
                'location' => 'Nairobi',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "The product knowledge and brush technique modules transformed my makeup application completely.",
                'is_featured' => true,
                'order' => 32,
            ],
            [
                'student_name' => 'Zulekha Hussein',
                'avatar_initials' => 'ZH',
                'role_title' => 'Lash Tech',
                'location' => 'Mombasa',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "The starter kit was filled with high-grade supplies. I was able to take clients immediately after graduation.",
                'is_featured' => true,
                'order' => 33,
            ],
            [
                'student_name' => 'Ines Uwineza',
                'avatar_initials' => 'IU',
                'role_title' => 'Freelance MUA',
                'location' => 'Kigali',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "The instructors truly care about student success. They guided me through every step of building my brand.",
                'is_featured' => true,
                'order' => 34,
            ],
            [
                'student_name' => 'Tabitha Maina',
                'avatar_initials' => 'TM',
                'role_title' => 'Volume Lash Artist',
                'location' => 'Nairobi',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "The volume fan creation techniques taught here are unmatched. Super clean and precise work.",
                'is_featured' => true,
                'order' => 35,
            ],
            [
                'student_name' => 'Ange Mukantwari',
                'avatar_initials' => 'AM',
                'role_title' => 'Certified Lash Tech',
                'location' => 'Kigali',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "I loved the focus on natural lash health and client safety. My clients keep coming back!",
                'is_featured' => true,
                'order' => 36,
            ],
            [
                'student_name' => 'Maureen Kamau',
                'avatar_initials' => 'MK',
                'role_title' => 'Bridal MUA',
                'location' => 'Nairobi',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "The bridal portfolio photoshoot at the end of the course gave me incredible pictures for my business website.",
                'is_featured' => true,
                'order' => 37,
            ],
            [
                'student_name' => 'Salma Rashid',
                'avatar_initials' => 'SR',
                'role_title' => 'Makeup Artist',
                'location' => 'Mombasa',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "Hands-down the best investment I've made for my beauty career in Kenya.",
                'is_featured' => true,
                'order' => 38,
            ],
            [
                'student_name' => 'Clarisse Ishimwe',
                'avatar_initials' => 'CI',
                'role_title' => 'Pro Makeup Artist',
                'location' => 'Kigali',
                'course_name' => 'Pro Makeup',
                'rating' => 5,
                'comment' => "From basic skin prep to advanced cut crease, the training curriculum is structured perfectly.",
                'is_featured' => true,
                'order' => 39,
            ],
            [
                'student_name' => 'Stacy Mwangi',
                'avatar_initials' => 'SM',
                'role_title' => 'Lash & Beauty Entrepreneur',
                'location' => 'Nairobi',
                'course_name' => 'Lashes Artistry',
                'rating' => 5,
                'comment' => "Diva House Beauty Academy gave me the skills, kit, and confidence to build my own profitable beauty business.",
                'is_featured' => true,
                'order' => 40,
            ],
        ];

        foreach ($reviews as $reviewData) {
            Review::updateOrCreate(
                ['student_name' => $reviewData['student_name']],
                $reviewData
            );
        }
    }
}
